### PR TITLE
Translating to Spanish 

### PR DESCRIPTION
**Pull request by migue802**
Hello! I have made a Spanish JSON file on `/src/languages/es.json`. 

Just wondering, is there any other file to translate apart from that?

### CODE REVIEW

**Comment by migue802** [comment]
Oh yeah forgot about intents lmao let me do it in a min

**Comment by Vexcited** [comment]
Hello ! Thanks you so much for your contribution !

Actually I didn't really expected to have another translation (but that's really cool) sooo I'll need to work on that.


Because currently, I check the language to use in every Alexa response (in intents)
I think I need to create a file who automatically gets to translation.

I'll do that when I'll have the time.
I can actually merge your pull request and work on this feature later.

Anyway, thanks you for contributing to the project !
I guess I'll need to do more updates 😂✨

**Comment by migue802** [comment]
That's nice! Anyways, I'm going to finish translating intents. Also, I think that I might help you with that once I finish this and read some code to understand it because I code JS every day but sometimes I don't get it 😂

**Comment by migue802** [comment]
And I think that's all the translations! Is there another file?

**Comment by Vexcited** [comment]
No, there's no more file ✨

I'll merge this PR now and when I'll have time (maybe tomorrow, I'll see depending of school) i will update the project to support more than two languages ~

I'll say it one more time ahahah~ but thanks you for contributing !

**Pull request merged**
